# 1er Programme

In [2]:
print("hello")

hello


In [3]:
print("eee")

eee


In [4]:
a=3+4
print(a)

7


In [5]:
type(2)

int

In [6]:
type("gt")

str

In [7]:
5+15

20

In [8]:
ma_liste=[1,2,3,'str',10.78]
print(type(ma_liste))
print(ma_liste)
print(ma_liste[3])

<class 'list'>
[1, 2, 3, 'str', 10.78]
str


In [9]:
ma_liste[1:2]
ma_liste[:4]

[1, 2, 3, 'str']

In [10]:
note={"m":34,
't':35,
'y':90,
'e':45}
print(note)

{'m': 34, 't': 35, 'y': 90, 'e': 45}


In [11]:
note["clé"]=6

In [12]:
print(note)

{'m': 34, 't': 35, 'y': 90, 'e': 45, 'clé': 6}


In [13]:
for cle in note.keys():
    print(cle)

m
t
y
e
clé


In [14]:
for val in note.values():
    print(val)

34
35
90
45
6


In [15]:
note.items()

dict_items([('m', 34), ('t', 35), ('y', 90), ('e', 45), ('clé', 6)])

In [16]:
for cle,val in note.items():
    print(cle,val)

m 34
t 35
y 90
e 45
clé 6


In [17]:
print(2==2)
print(1!=1)
print(5<8)
print(11>=11)

True
False
True
True


In [18]:
print((3==3) and (4==4))
print((4==5) and (4==2))
print((4==4) or (5==5))
print((5==2) or (6==6))

True
False
True
True


In [19]:
help(note)

Help on dict object:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Built-in subclasses:
 |      StgDict
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>va

In [20]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [21]:
print(22,end="v") #test

22v

In [22]:
import numpy as np 
ntab=np.array([1,2,3,4,5,6,7,8,9,0,12,13,14,15,16,17,18,19,20,21,22,23,24])#affiche un tableau
print(ntab)
type(ntab)#affiche le type de varriables

[ 1  2  3  4  5  6  7  8  9  0 12 13 14 15 16 17 18 19 20 21 22 23 24]


numpy.ndarray

In [23]:
ntab2=np.array([[1,2,3],[4,5,6],[7,8,9]])#tableau 2dimension
print(ntab2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
ntab2.dtype

dtype('int64')

In [32]:
ntab3=np.genfromtxt('csv/iris.csv',delimiter=';',skip_header=True)
print(ntab3)

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan]


In [43]:
#import pandas as pd
#ntab4=np.genfromtxt("athlete_events.csv",delimiter=";",skip_header=True)
result = pd.read_csv('csv/athlete_events.csv')
print(result)

            ID                      Name Sex   Age  Height  Weight  \
0            1                 A Dijiang   M  24.0   180.0    80.0   
1            2                  A Lamusi   M  23.0   170.0    60.0   
2            3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN   
3            4      Edgar Lindenau Aabye   M  34.0     NaN     NaN   
4            5  Christine Jacoba Aaftink   F  21.0   185.0    82.0   
...        ...                       ...  ..   ...     ...     ...   
271111  135569                Andrzej ya   M  29.0   179.0    89.0   
271112  135570                  Piotr ya   M  27.0   176.0    59.0   
271113  135570                  Piotr ya   M  27.0   176.0    59.0   
271114  135571        Tomasz Ireneusz ya   M  30.0   185.0    96.0   
271115  135571        Tomasz Ireneusz ya   M  34.0   185.0    96.0   

                  Team  NOC        Games  Year  Season            City  \
0                China  CHN  1992 Summer  1992  Summer       Barcelona   
1          

In [42]:
reader = pd.read_csv('csv/iris.csv')

print(reader)

     Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
0             1           5.1          3.5           1.4          0.2   
1             2           4.9          3.0           1.4          0.2   
2             3           4.7          3.2           1.3          0.2   
3             4           4.6          3.1           1.5          0.2   
4             5           5.0          3.6           1.4          0.2   
..          ...           ...          ...           ...          ...   
145         146           6.7          3.0           5.2          2.3   
146         147           6.3          2.5           5.0          1.9   
147         148           6.5          3.0           5.2          2.0   
148         149           6.2          3.4           5.4          2.3   
149         150           5.9          3.0           5.1          1.8   

       Species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 