NUMPY
Package utilisé pour le calcul scientifique

In [1]:
import numpy as np 
#import pandas as pd
ntab=np.array([1,2,3,4,5,6,7,8,9,0,12,13,14,15,16,17,18,19,20,21,22,23,24])#affiche un tableau
print(ntab)
type(ntab)#affiche le type de varriables

[ 1  2  3  4  5  6  7  8  9  0 12 13 14 15 16 17 18 19 20 21 22 23 24]


numpy.ndarray

In [2]:
ntab2=np.array([[1,2,3],[4,5,6],[7,8,9]])#tableau 2dimension affichage
print(ntab2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
ntab2.dtype# afficher le type d'une variable


dtype('int64')

In [5]:
import pandas as pd
result = pd.read_csv('csv/athlete_events.csv')# lire un csv
print(result)

            ID                      Name Sex   Age  Height  Weight  \
0            1                 A Dijiang   M  24.0   180.0    80.0   
1            2                  A Lamusi   M  23.0   170.0    60.0   
2            3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN   
3            4      Edgar Lindenau Aabye   M  34.0     NaN     NaN   
4            5  Christine Jacoba Aaftink   F  21.0   185.0    82.0   
...        ...                       ...  ..   ...     ...     ...   
271111  135569                Andrzej ya   M  29.0   179.0    89.0   
271112  135570                  Piotr ya   M  27.0   176.0    59.0   
271113  135570                  Piotr ya   M  27.0   176.0    59.0   
271114  135571        Tomasz Ireneusz ya   M  30.0   185.0    96.0   
271115  135571        Tomasz Ireneusz ya   M  34.0   185.0    96.0   

                  Team  NOC        Games  Year  Season            City  \
0                China  CHN  1992 Summer  1992  Summer       Barcelona   
1          

In [7]:
result2 = pd.read_csv('csv/iris.csv')
print(result2)

     Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
0             1           5.1          3.5           1.4          0.2   
1             2           4.9          3.0           1.4          0.2   
2             3           4.7          3.2           1.3          0.2   
3             4           4.6          3.1           1.5          0.2   
4             5           5.0          3.6           1.4          0.2   
..          ...           ...          ...           ...          ...   
145         146           6.7          3.0           5.2          2.3   
146         147           6.3          2.5           5.0          1.9   
147         148           6.5          3.0           5.2          2.0   
148         149           6.2          3.4           5.4          2.3   
149         150           5.9          3.0           5.1          1.8   

       Species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 

In [23]:
iris=np.genfromtxt('csv/iris.csv',delimiter=';',skip_header=True)
print(iris)

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan]


In [24]:
iris[2,1]=4

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed